// src/lib/location/iana.ts
// Расширенный список IANA timezones
// Без алиасов типа US/Eastern — только canonical зоны.

export const IANA_TIMEZONES: string[] = [

    /* UTC */
    'UTC',

    /* Europe */
    'Europe/London',
    'Europe/Dublin',
    'Europe/Lisbon',
    'Europe/Madrid',
    'Europe/Paris',
    'Europe/Brussels',
    'Europe/Amsterdam',
    'Europe/Luxembourg',
    'Europe/Berlin',
    'Europe/Zurich',
    'Europe/Vienna',
    'Europe/Rome',
    'Europe/Monaco',
    'Europe/Prague',
    'Europe/Warsaw',
    'Europe/Budapest',
    'Europe/Bratislava',
    'Europe/Ljubljana',
    'Europe/Zagreb',
    'Europe/Belgrade',
    'Europe/Sarajevo',
    'Europe/Skopje',
    'Europe/Tirane',
    'Europe/Athens',
    'Europe/Sofia',
    'Europe/Bucharest',
    'Europe/Helsinki',
    'Europe/Stockholm',
    'Europe/Oslo',
    'Europe/Copenhagen',
    'Europe/Tallinn',
    'Europe/Riga',
    'Europe/Vilnius',
    'Europe/Minsk',
    'Europe/Kiev',
    'Europe/Chisinau',
    'Europe/Moscow',
    'Europe/Kaliningrad',
    'Europe/Istanbul',

    /* Americas — North */
    'America/St_Johns',
    'America/Halifax',
    'America/Moncton',
    'America/Toronto',
    'America/Montreal',
    'America/Winnipeg',
    'America/Regina',
    'America/Edmonton',
    'America/Calgary',
    'America/Vancouver',
    'America/Whitehorse',
    'America/New_York',
    'America/Detroit',
    'America/Chicago',
    'America/Minneapolis',
    'America/Denver',
    'America/Phoenix',
    'America/Los_Angeles',
    'America/Anchorage',
    'America/Adak',
    'Pacific/Honolulu',

    /* Americas — Central */
    'America/Mexico_City',
    'America/Cancun',
    'America/Guatemala',
    'America/Belize',
    'America/Tegucigalpa',
    'America/Managua',
    'America/Costa_Rica',
    'America/Panama',
    'America/Havana',

    /* Americas — South */
    'America/Bogota',
    'America/Lima',
    'America/Caracas',
    'America/La_Paz',
    'America/Santiago',
    'America/Asuncion',
    'America/Buenos_Aires',
    'America/Montevideo',
    'America/Sao_Paulo',
    'America/Rio_Branco',
    'America/Campo_Grande',
    'America/Manaus',
    'America/Recife',
    'America/Fortaleza',
    'America/Belem',

    /* Africa */
    'Africa/Casablanca',
    'Africa/Algiers',
    'Africa/Tunis',
    'Africa/Tripoli',
    'Africa/Cairo',
    'Africa/Khartoum',
    'Africa/Nairobi',
    'Africa/Addis_Ababa',
    'Africa/Dar_es_Salaam',
    'Africa/Kampala',
    'Africa/Lagos',
    'Africa/Accra',
    'Africa/Dakar',
    'Africa/Abidjan',
    'Africa/Johannesburg',
    'Africa/Windhoek',
    'Africa/Harare',

    /* Middle East */
    'Asia/Jerusalem',
    'Asia/Beirut',
    'Asia/Damascus',
    'Asia/Amman',
    'Asia/Baghdad',
    'Asia/Riyadh',
    'Asia/Qatar',
    'Asia/Bahrain',
    'Asia/Kuwait',
    'Asia/Dubai',
    'Asia/Muscat',
    'Asia/Tehran',

    /* Central Asia */
    'Asia/Tbilisi',
    'Asia/Yerevan',
    'Asia/Baku',
    'Asia/Ashgabat',
    'Asia/Tashkent',
    'Asia/Samarkand',
    'Asia/Bishkek',
    'Asia/Almaty',

    /* South Asia */
    'Asia/Kabul',
    'Asia/Karachi',
    'Asia/Colombo',
    'Asia/Kolkata',
    'Asia/Kathmandu',
    'Asia/Dhaka',

    /* Southeast Asia */
    'Asia/Yangon',
    'Asia/Bangkok',
    'Asia/Ho_Chi_Minh',
    'Asia/Phnom_Penh',
    'Asia/Vientiane',
    'Asia/Kuala_Lumpur',
    'Asia/Singapore',
    'Asia/Jakarta',
    'Asia/Manila',

    /* East Asia */
    'Asia/Hong_Kong',
    'Asia/Macau',
    'Asia/Shanghai',
    'Asia/Taipei',
    'Asia/Seoul',
    'Asia/Tokyo',

    /* Australia / Pacific */
    'Australia/Perth',
    'Australia/Adelaide',
    'Australia/Darwin',
    'Australia/Brisbane',
    'Australia/Sydney',
    'Australia/Hobart',
    'Pacific/Guam',
    'Pacific/Port_Moresby',
    'Pacific/Auckland',
    'Pacific/Fiji',
    'Pacific/Tahiti'
];
